services:
  top-sales-dashboard:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/opt/top-sales-dashboard"
      - "/opt/top-sales-dashboard/node_modules"
    environment:
      - NEXT_WEBPACK_USEPOLLING=true
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
